name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi Welcome to the first issue! Hope you have fun here!'' first issue'
        pr-message: 'Hi, Thanks for your contribution! We are really grateful that you found this Project worth your time! keep contributing!!'' first pr'
